# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/file_item_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(330, 204)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(330, 0))
        Form.setMaximumSize(QtCore.QSize(330, 500))
        Form.setStyleSheet("QWidget{\n"
"    background-color: rgb(57, 57, 57);\n"
"}\n"
"QGroupBox {\n"
"    background-color:rgb(57, 57, 57);\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(33, 33, 33);\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    background-color: rgba(57, 57, 57, 0);\n"
"    margin: -5px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top  left; \n"
"    padding: 0 6px;\n"
"    color: white;\n"
"}\n"
"\n"
"QGroupBox::indicator {\n"
"    width: 24px;\n"
"    height: 24px;\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked {\n"
"    image: url(:/icons/Media/Icons/chevron-right-outline.svg);\n"
"}\n"
"\n"
"QGroupBox::indicator:checked {\n"
"    image: url(:/icons/Media/Icons/chevron-down-outline.svg);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(134, 134, 134);\n"
"    color: black;\n"
"    border: 1px solid rgb(33, 33, 33);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton#bt_reload_gcode,\n"
"QPushButton#bt_top_generate_gcode{\n"
"    background-color: rgb(97, 192, 87);\n"
"}\n"
"\n"
"QPushButton#bt_delete_file{\n"
"    background-color: rgb(160, 49, 46);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid rgb(70, 70, 70);\n"
"    border-radius: 3px;\n"
"    padding: 0 8px;\n"
"    background: rgb(41, 41, 41);\n"
"    selection-background-color: darkgray;\n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 12, -1, 5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bt_top_generate_gcode = QtWidgets.QPushButton(self.groupBox)
        self.bt_top_generate_gcode.setMaximumSize(QtCore.QSize(40, 25))
        self.bt_top_generate_gcode.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Media/Icons/sync-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_top_generate_gcode.setIcon(icon)
        self.bt_top_generate_gcode.setObjectName("bt_top_generate_gcode")
        self.horizontalLayout_3.addWidget(self.bt_top_generate_gcode)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bt_hide_show_gcode = QtWidgets.QPushButton(self.groupBox)
        self.bt_hide_show_gcode.setMaximumSize(QtCore.QSize(40, 25))
        self.bt_hide_show_gcode.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Media/Icons/eye-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_hide_show_gcode.setIcon(icon1)
        self.bt_hide_show_gcode.setIconSize(QtCore.QSize(24, 24))
        self.bt_hide_show_gcode.setObjectName("bt_hide_show_gcode")
        self.horizontalLayout_3.addWidget(self.bt_hide_show_gcode)
        self.bt_move_down = QtWidgets.QPushButton(self.groupBox)
        self.bt_move_down.setMaximumSize(QtCore.QSize(40, 25))
        self.bt_move_down.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Media/Icons/arrow-down-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_move_down.setIcon(icon2)
        self.bt_move_down.setIconSize(QtCore.QSize(20, 20))
        self.bt_move_down.setObjectName("bt_move_down")
        self.horizontalLayout_3.addWidget(self.bt_move_down)
        self.bt_move_up = QtWidgets.QPushButton(self.groupBox)
        self.bt_move_up.setMaximumSize(QtCore.QSize(40, 25))
        self.bt_move_up.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Media/Icons/arrow-up-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_move_up.setIcon(icon3)
        self.bt_move_up.setIconSize(QtCore.QSize(20, 20))
        self.bt_move_up.setObjectName("bt_move_up")
        self.horizontalLayout_3.addWidget(self.bt_move_up)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.bt_delete_file = QtWidgets.QPushButton(self.groupBox)
        self.bt_delete_file.setMaximumSize(QtCore.QSize(40, 25))
        self.bt_delete_file.setStyleSheet("")
        self.bt_delete_file.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Media/Icons/trash-2-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_delete_file.setIcon(icon4)
        self.bt_delete_file.setIconSize(QtCore.QSize(20, 20))
        self.bt_delete_file.setObjectName("bt_delete_file")
        self.horizontalLayout_3.addWidget(self.bt_delete_file)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.setStretch(4, 1)
        self.horizontalLayout_3.setStretch(6, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.config_frame = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_frame.sizePolicy().hasHeightForWidth())
        self.config_frame.setSizePolicy(sizePolicy)
        self.config_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.config_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.config_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.config_frame.setObjectName("config_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.config_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.config_frame)
        self.label.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_feed_rate = QtWidgets.QLineEdit(self.config_frame)
        self.le_feed_rate.setMinimumSize(QtCore.QSize(100, 20))
        self.le_feed_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.le_feed_rate.setObjectName("le_feed_rate")
        self.horizontalLayout.addWidget(self.le_feed_rate)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.config_frame)
        self.label_2.setMinimumSize(QtCore.QSize(65, 0))
        self.label_2.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.hs_power = QtWidgets.QSlider(self.config_frame)
        self.hs_power.setMaximum(100)
        self.hs_power.setSingleStep(25)
        self.hs_power.setProperty("value", 25)
        self.hs_power.setTracking(True)
        self.hs_power.setOrientation(QtCore.Qt.Horizontal)
        self.hs_power.setInvertedAppearance(False)
        self.hs_power.setInvertedControls(False)
        self.hs_power.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hs_power.setTickInterval(25)
        self.hs_power.setObjectName("hs_power")
        self.horizontalLayout_2.addWidget(self.hs_power)
        self.le_power = QtWidgets.QLineEdit(self.config_frame)
        self.le_power.setMinimumSize(QtCore.QSize(0, 20))
        self.le_power.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le_power.setAlignment(QtCore.Qt.AlignCenter)
        self.le_power.setObjectName("le_power")
        self.horizontalLayout_2.addWidget(self.le_power)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.config_frame)
        self.label_3.setMinimumSize(QtCore.QSize(65, 0))
        self.label_3.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.le_passes = QtWidgets.QLineEdit(self.config_frame)
        self.le_passes.setMinimumSize(QtCore.QSize(100, 20))
        self.le_passes.setAlignment(QtCore.Qt.AlignCenter)
        self.le_passes.setObjectName("le_passes")
        self.horizontalLayout_4.addWidget(self.le_passes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.lb_power_coef = QtWidgets.QLabel(self.config_frame)
        self.lb_power_coef.setMinimumSize(QtCore.QSize(0, 20))
        self.lb_power_coef.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lb_power_coef.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_power_coef.setObjectName("lb_power_coef")
        self.verticalLayout_2.addWidget(self.lb_power_coef)
        self.bt_reload_gcode = QtWidgets.QPushButton(self.config_frame)
        self.bt_reload_gcode.setMinimumSize(QtCore.QSize(0, 30))
        self.bt_reload_gcode.setMaximumSize(QtCore.QSize(16777215, 32))
        self.bt_reload_gcode.setIcon(icon)
        self.bt_reload_gcode.setIconSize(QtCore.QSize(20, 20))
        self.bt_reload_gcode.setObjectName("bt_reload_gcode")
        self.verticalLayout_2.addWidget(self.bt_reload_gcode)
        self.verticalLayout_3.addWidget(self.config_frame)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "File Config"))
        self.groupBox.setTitle(_translate("Form", "FileName.svg"))
        self.label.setText(_translate("Form", "Feed Rate:"))
        self.label_2.setText(_translate("Form", "Power:"))
        self.label_3.setText(_translate("Form", "Passes:"))
        self.lb_power_coef.setText(_translate("Form", "Power Coef.: --"))
        self.bt_reload_gcode.setText(_translate("Form", "Reload Gcode"))
import icons_rc
